Updated script to pass shell check

diff --git a/Terraform Manager/tfmanage b/Terraform Manager/tfmanage
--- a/Terraform Manager/tfmanage
+++ b/Terraform Manager/tfmanage
@@ -17,29 +17,40 @@
 ARG=$1
 TARGETVER=$2
 
-TFMVER="0.1.2"
+TFMVER="0.1.3"
 
 function detectos() {
-    if [ "$(uname)" == "Darwin" ]; then
-        # Do something under Mac OS X platform
-        KERNEL="darwin"
-        INSTPATH="/usr/local/bin"
-        echo "----- TFManage: OS Detected as MacOS"
-    elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
-        KERNEL="linux"
-        INSTPATH="/usr/bin"
-        echo "----- TFManage: OS Detected as Linux"
-    elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
-        # Do something under 32 bits Windows NT platform
-        echo "----- TFManage: OS Detected as Windows (32-Bit)"
-        >&2 echo "This script currently does not support Win32"
-        exit 1
-    elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
-        # Do something under 64 bits Windows NT platform
-        echo "----- TFManage: OS Detected as Windows (64-Bit)"
-        >&2 echo "This script currently does not support Win64"
-        exit 1
-    fi
+
+	if [[ "${OSTYPE}" == "linux-gnu" ]]; then
+		KERNEL="linux"
+		INSTPATH="/usr/bin"
+		echo "----- TFManage: OS Detected as Linux"
+	elif [[ "${OSTYPE}" == "darwin"* ]]; then
+		KERNEL="darwin"
+		INSTPATH="/usr/local/bin"
+		echo "----- TFManage: OS Detected as MacOS"
+	elif [[ "${OSTYPE}" == "cygwin" ]]; then
+		echo "----- TFManage: OS Detected as Windows (running Cygwin)"
+		>&2 echo "This script currently does not support Cygwin"
+		exit 1
+	elif [[ "${OSTYPE}" == "msys" ]]; then
+		echo "----- TFManage: OS Detected as Windows (Git Bash)"
+		>&2 echo "This script currently does not support Windows"
+		exit 1
+	elif [[ "${OSTYPE}" == "win32" ]]; then
+		echo "----- TFManage: OS Detected as Windows"
+		>&2 echo "This script currently does not support Windows"
+		exit 1
+	elif [[ "${OSTYPE}" == "freebsd"* ]]; then
+		echo "----- TFManage: OS Detected as FreeBSD"
+		>&2 echo "This script currently does not support FreeBSD"
+		exit 1
+	else
+		echo "----- TFManage: OS Not Detected"
+		>&2 echo "The script was unable to detect your OS ${OSTYPE}"
+		exit 1
+	fi
+
 }
 
 function currentversion() {
